### ISSUE TITLE
Digital Clock Font

### ISSUE THREAD

**Issue by dave782** [jsanjose/streamdeck_digital_clock#2]
I really like the simplicity of the Digital Clock.
Is there a way to change the Font though?
I'm really new to this, so sorry if there's an obvious way to do it, i only figured out how to change the color so far

**Comment by jsanjose** [comment]
No, there's no option to change font because the clock doesn't use fonts. It simulates a digital clock with 7 segments per digit. Like the old ones.

If you want a clock that allows you to use diferent fonts I suggest the BarRaider's World Time plugin (https://github.com/BarRaider/streamdeck-worldtime/)
